import type { CollectionConfig } from 'payload'

export const Companies: CollectionConfig = {
  slug: 'companies',
  admin: {
    useAsTitle: 'name',
  },
  fields: [
    {
      name: 'name',
      type: 'text',
      required: true,
      label: 'Unternehmensname',
    },
    {
      name: 'slug',
      type: 'text',
      required: true,
      unique: true,
      admin: {
        description: 'URL-freundlicher Name',
      },
    },
    {
      name: 'logo',
      type: 'upload',
      relationTo: 'media',
      label: 'Logo (Upload)',
    },
    {
      name: 'logoUrl',
      type: 'text',
      label: 'Logo URL (External)',
      admin: {
        description: 'External logo URL from CompanyEnrich API',
      },
    },
    {
      name: 'description',
      type: 'richText',
      label: 'Beschreibung',
    },
    {
      name: 'website',
      type: 'text',
      label: 'Website',
    },
    {
      name: 'industry',
      type: 'select',
      label: 'Branche',
      options: [
        { label: 'IT & Software', value: 'it' },
        { label: 'Finanzen & Banking', value: 'finance' },
        { label: 'Gesundheitswesen', value: 'healthcare' },
        { label: 'Industrie & Produktion', value: 'manufacturing' },
        { label: 'Handel & Verkauf', value: 'retail' },
        { label: 'Marketing & Kommunikation', value: 'marketing' },
        { label: 'Bildung & Forschung', value: 'education' },
        { label: 'Beratung & Consulting', value: 'consulting' },
        { label: 'Hotellerie & Gastronomie', value: 'hospitality' },
        { label: 'Transport & Logistik', value: 'logistics' },
        { label: 'Bau & Immobilien', value: 'construction' },
        { label: 'Andere', value: 'other' },
      ],
    },
    {
      name: 'size',
      type: 'select',
      label: 'Unternehmensgrösse',
      options: [
        { label: '1-10 Mitarbeiter', value: '1-10' },
        { label: '11-50 Mitarbeiter', value: '11-50' },
        { label: '51-200 Mitarbeiter', value: '51-200' },
        { label: '201-500 Mitarbeiter', value: '201-500' },
        { label: '501-1000 Mitarbeiter', value: '501-1000' },
        { label: '1000+ Mitarbeiter', value: '1000+' },
      ],
    },
    {
      name: 'location',
      type: 'group',
      label: 'Standort',
      fields: [
        {
          name: 'city',
          type: 'text',
          label: 'Stadt',
        },
        {
          name: 'canton',
          type: 'select',
          label: 'Kanton',
          options: [
            { label: 'Zürich', value: 'ZH' },
            { label: 'Bern', value: 'BE' },
            { label: 'Luzern', value: 'LU' },
            { label: 'Uri', value: 'UR' },
            { label: 'Schwyz', value: 'SZ' },
            { label: 'Obwalden', value: 'OW' },
            { label: 'Nidwalden', value: 'NW' },
            { label: 'Glarus', value: 'GL' },
            { label: 'Zug', value: 'ZG' },
            { label: 'Freiburg', value: 'FR' },
            { label: 'Solothurn', value: 'SO' },
            { label: 'Basel-Stadt', value: 'BS' },
            { label: 'Basel-Landschaft', value: 'BL' },
            { label: 'Schaffhausen', value: 'SH' },
            { label: 'Appenzell Ausserrhoden', value: 'AR' },
            { label: 'Appenzell Innerrhoden', value: 'AI' },
            { label: 'St. Gallen', value: 'SG' },
            { label: 'Graubünden', value: 'GR' },
            { label: 'Aargau', value: 'AG' },
            { label: 'Thurgau', value: 'TG' },
            { label: 'Tessin', value: 'TI' },
            { label: 'Waadt', value: 'VD' },
            { label: 'Wallis', value: 'VS' },
            { label: 'Neuenburg', value: 'NE' },
            { label: 'Genf', value: 'GE' },
            { label: 'Jura', value: 'JU' },
          ],
        },
      ],
    },
  ],
  timestamps: true,
}
