import type { CollectionConfig } from 'payload'

export const Jobs: CollectionConfig = {
  slug: 'jobs',
  admin: {
    useAsTitle: 'title',
    defaultColumns: ['title', 'company', 'status', 'publishedAt'],
  },
  fields: [
    {
      name: 'title',
      type: 'text',
      required: true,
      label: 'Stellentitel',
    },
    {
      name: 'slug',
      type: 'text',
      required: true,
      unique: true,
      admin: {
        description: 'URL-freundlicher Name',
      },
    },
    {
      name: 'company',
      type: 'relationship',
      relationTo: 'companies',
      required: true,
      label: 'Unternehmen',
    },
    {
      name: 'description',
      type: 'richText',
      required: true,
      label: 'Stellenbeschreibung',
    },
    {
      name: 'shortDescription',
      type: 'textarea',
      label: 'Kurzbeschreibung',
      maxLength: 300,
    },
    {
      name: 'category',
      type: 'select',
      label: 'Kategorie',
      required: true,
      options: [
        { label: 'IT & Software', value: 'it' },
        { label: 'Finanzen & Banking', value: 'finance' },
        { label: 'Gesundheitswesen', value: 'healthcare' },
        { label: 'Industrie & Produktion', value: 'manufacturing' },
        { label: 'Handel & Verkauf', value: 'retail' },
        { label: 'Marketing & Kommunikation', value: 'marketing' },
        { label: 'Bildung & Forschung', value: 'education' },
        { label: 'Beratung & Consulting', value: 'consulting' },
        { label: 'Hotellerie & Gastronomie', value: 'hospitality' },
        { label: 'Transport & Logistik', value: 'logistics' },
        { label: 'Bau & Immobilien', value: 'construction' },
        { label: 'Administration & Büro', value: 'admin' },
        { label: 'HR & Personal', value: 'hr' },
        { label: 'Recht', value: 'legal' },
        { label: 'Andere', value: 'other' },
      ],
    },
    {
      name: 'externalId',
      type: 'text',
      label: 'External ID',
      unique: true,
      admin: {
        description: 'ID from external job source (e.g. SwissDevJobs)',
        position: 'sidebar',
      },
    },
    {
      name: 'experienceLevel',
      type: 'select',
      label: 'Erfahrungsstufe',
      options: [
        { label: 'Junior', value: 'junior' },
        { label: 'Regular', value: 'regular' },
        { label: 'Senior', value: 'senior' },
        { label: 'Lead', value: 'lead' },
      ],
    },
    {
      name: 'location',
      type: 'group',
      label: 'Arbeitsort',
      fields: [
        {
          name: 'city',
          type: 'text',
          label: 'Stadt',
          required: true,
        },
        {
          name: 'canton',
          type: 'select',
          label: 'Kanton',
          required: true,
          options: [
            { label: 'Zürich', value: 'ZH' },
            { label: 'Bern', value: 'BE' },
            { label: 'Luzern', value: 'LU' },
            { label: 'Uri', value: 'UR' },
            { label: 'Schwyz', value: 'SZ' },
            { label: 'Obwalden', value: 'OW' },
            { label: 'Nidwalden', value: 'NW' },
            { label: 'Glarus', value: 'GL' },
            { label: 'Zug', value: 'ZG' },
            { label: 'Freiburg', value: 'FR' },
            { label: 'Solothurn', value: 'SO' },
            { label: 'Basel-Stadt', value: 'BS' },
            { label: 'Basel-Landschaft', value: 'BL' },
            { label: 'Schaffhausen', value: 'SH' },
            { label: 'Appenzell Ausserrhoden', value: 'AR' },
            { label: 'Appenzell Innerrhoden', value: 'AI' },
            { label: 'St. Gallen', value: 'SG' },
            { label: 'Graubünden', value: 'GR' },
            { label: 'Aargau', value: 'AG' },
            { label: 'Thurgau', value: 'TG' },
            { label: 'Tessin', value: 'TI' },
            { label: 'Waadt', value: 'VD' },
            { label: 'Wallis', value: 'VS' },
            { label: 'Neuenburg', value: 'NE' },
            { label: 'Genf', value: 'GE' },
            { label: 'Jura', value: 'JU' },
          ],
        },
        {
          name: 'address',
          type: 'text',
          label: 'Adresse',
        },
        {
          name: 'postalCode',
          type: 'text',
          label: 'PLZ',
        },
        {
          name: 'latitude',
          type: 'number',
          label: 'Breitengrad',
        },
        {
          name: 'longitude',
          type: 'number',
          label: 'Längengrad',
        },
      ],
    },
    {
      name: 'employmentType',
      type: 'select',
      label: 'Anstellungsart',
      required: true,
      options: [
        { label: 'Festanstellung', value: 'permanent' },
        { label: 'Temporär', value: 'temporary' },
        { label: 'Freelance', value: 'freelance' },
        { label: 'Praktikum', value: 'internship' },
        { label: 'Lehrstelle', value: 'apprenticeship' },
      ],
    },
    {
      name: 'workload',
      type: 'group',
      label: 'Pensum',
      fields: [
        {
          name: 'min',
          type: 'number',
          label: 'Minimum (%)',
          min: 0,
          max: 100,
          defaultValue: 80,
        },
        {
          name: 'max',
          type: 'number',
          label: 'Maximum (%)',
          min: 0,
          max: 100,
          defaultValue: 100,
        },
      ],
    },
    {
      name: 'workModel',
      type: 'select',
      label: 'Arbeitsmodell',
      options: [
        { label: 'Vor Ort', value: 'onsite' },
        { label: 'Hybrid', value: 'hybrid' },
        { label: 'Remote', value: 'remote' },
      ],
    },
    {
      name: 'salary',
      type: 'group',
      label: 'Gehalt',
      fields: [
        {
          name: 'min',
          type: 'number',
          label: 'Minimum (CHF/Jahr)',
        },
        {
          name: 'max',
          type: 'number',
          label: 'Maximum (CHF/Jahr)',
        },
        {
          name: 'isPublic',
          type: 'checkbox',
          label: 'Gehalt öffentlich anzeigen',
          defaultValue: false,
        },
      ],
    },
    {
      name: 'responsibilities',
      type: 'richText',
      label: 'Aufgaben',
    },
    {
      name: 'requirements',
      type: 'richText',
      label: 'Anforderungen',
    },
    {
      name: 'benefits',
      type: 'richText',
      label: 'Was wir bieten',
    },
    {
      name: 'skills',
      type: 'array',
      label: 'Erforderliche Skills',
      fields: [
        {
          name: 'skill',
          type: 'text',
        },
      ],
    },
    {
      name: 'applicationUrl',
      type: 'text',
      label: 'Externe Bewerbungs-URL',
      admin: {
        description: 'Falls Bewerbungen extern erfolgen sollen',
      },
    },
    {
      name: 'applicationEmail',
      type: 'email',
      label: 'Bewerbungs-E-Mail',
    },
    {
      name: 'status',
      type: 'select',
      label: 'Status',
      required: true,
      defaultValue: 'draft',
      options: [
        { label: 'Entwurf', value: 'draft' },
        { label: 'Aktiv', value: 'active' },
        { label: 'Abgelaufen', value: 'expired' },
        { label: 'Geschlossen', value: 'closed' },
      ],
      admin: {
        position: 'sidebar',
      },
    },
    {
      name: 'publishedAt',
      type: 'date',
      label: 'Veröffentlicht am',
      admin: {
        position: 'sidebar',
        date: {
          pickerAppearance: 'dayOnly',
        },
      },
    },
    {
      name: 'expiresAt',
      type: 'date',
      label: 'Läuft ab am',
      admin: {
        position: 'sidebar',
        date: {
          pickerAppearance: 'dayOnly',
        },
      },
    },
    {
      name: 'featured',
      type: 'checkbox',
      label: 'Hervorgehoben',
      defaultValue: false,
      admin: {
        position: 'sidebar',
      },
    },
  ],
  timestamps: true,
}
