/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    jobs: Job;
    companies: Company;
    media: Media;
    applications: Application;
    'candidate-profiles': CandidateProfile;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    'candidate-profiles': CandidateProfilesSelect<false> | CandidateProfilesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  /**
   * Rolle des Benutzers
   */
  role: 'candidate' | 'employer' | 'admin';
  /**
   * Unternehmen (nur für Arbeitgeber)
   */
  company?: (number | null) | Company;
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  name: string;
  /**
   * URL-freundlicher Name
   */
  slug: string;
  logo?: (number | null) | Media;
  /**
   * External logo URL from CompanyEnrich API
   */
  logoUrl?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  website?: string | null;
  industry?:
    | (
        | 'it'
        | 'finance'
        | 'healthcare'
        | 'manufacturing'
        | 'retail'
        | 'marketing'
        | 'education'
        | 'consulting'
        | 'hospitality'
        | 'logistics'
        | 'construction'
        | 'other'
      )
    | null;
  size?: ('1-10' | '11-50' | '51-200' | '201-500' | '501-1000' | '1000+') | null;
  location?: {
    city?: string | null;
    canton?:
      | (
          | 'ZH'
          | 'BE'
          | 'LU'
          | 'UR'
          | 'SZ'
          | 'OW'
          | 'NW'
          | 'GL'
          | 'ZG'
          | 'FR'
          | 'SO'
          | 'BS'
          | 'BL'
          | 'SH'
          | 'AR'
          | 'AI'
          | 'SG'
          | 'GR'
          | 'AG'
          | 'TG'
          | 'TI'
          | 'VD'
          | 'VS'
          | 'NE'
          | 'GE'
          | 'JU'
        )
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  /**
   * URL-freundlicher Name
   */
  slug: string;
  company: number | Company;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  shortDescription?: string | null;
  category:
    | 'it'
    | 'finance'
    | 'healthcare'
    | 'manufacturing'
    | 'retail'
    | 'marketing'
    | 'education'
    | 'consulting'
    | 'hospitality'
    | 'logistics'
    | 'construction'
    | 'admin'
    | 'hr'
    | 'legal'
    | 'other';
  /**
   * ID from external job source (e.g. SwissDevJobs)
   */
  externalId?: string | null;
  experienceLevel?: ('junior' | 'regular' | 'senior' | 'lead') | null;
  location: {
    city: string;
    canton:
      | 'ZH'
      | 'BE'
      | 'LU'
      | 'UR'
      | 'SZ'
      | 'OW'
      | 'NW'
      | 'GL'
      | 'ZG'
      | 'FR'
      | 'SO'
      | 'BS'
      | 'BL'
      | 'SH'
      | 'AR'
      | 'AI'
      | 'SG'
      | 'GR'
      | 'AG'
      | 'TG'
      | 'TI'
      | 'VD'
      | 'VS'
      | 'NE'
      | 'GE'
      | 'JU';
    address?: string | null;
    postalCode?: string | null;
    latitude?: number | null;
    longitude?: number | null;
  };
  employmentType: 'permanent' | 'temporary' | 'freelance' | 'internship' | 'apprenticeship';
  workload?: {
    min?: number | null;
    max?: number | null;
  };
  workModel?: ('onsite' | 'hybrid' | 'remote') | null;
  salary?: {
    min?: number | null;
    max?: number | null;
    isPublic?: boolean | null;
  };
  responsibilities?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  requirements?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  benefits?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  skills?:
    | {
        skill?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Falls Bewerbungen extern erfolgen sollen
   */
  applicationUrl?: string | null;
  applicationEmail?: string | null;
  status: 'draft' | 'active' | 'expired' | 'closed';
  publishedAt?: string | null;
  expiresAt?: string | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  job: number | Job;
  candidate: number | User;
  status: 'new' | 'reviewed' | 'interview' | 'offer' | 'rejected' | 'hired' | 'withdrawn';
  message?: string | null;
  cv?: (number | null) | Media;
  coverLetter?: (number | null) | Media;
  /**
   * Nur für Arbeitgeber sichtbar
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidate-profiles".
 */
export interface CandidateProfile {
  id: number;
  user: number | User;
  summary?: string | null;
  experiences?:
    | {
        title: string;
        company: string;
        location?: string | null;
        startDate: string;
        endDate?: string | null;
        current?: boolean | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  education?:
    | {
        degree: string;
        institution: string;
        field?: string | null;
        startDate?: string | null;
        endDate?: string | null;
        id?: string | null;
      }[]
    | null;
  skills?:
    | {
        name: string;
        level?: ('beginner' | 'intermediate' | 'expert') | null;
        id?: string | null;
      }[]
    | null;
  languages?:
    | {
        language: string;
        level?: ('basic' | 'intermediate' | 'fluent' | 'native') | null;
        id?: string | null;
      }[]
    | null;
  preferences?: {
    desiredRole?: string | null;
    desiredSalary?: number | null;
    desiredWorkload?: {
      min?: number | null;
      max?: number | null;
    };
    desiredLocations?:
      | {
          location?: string | null;
          id?: string | null;
        }[]
      | null;
    workModels?: ('onsite' | 'hybrid' | 'remote')[] | null;
    availableFrom?: string | null;
  };
  cvFile?: (number | null) | Media;
  /**
   * Wenn aktiv, können Arbeitgeber Ihr Profil im Talentpool finden
   */
  isPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'candidate-profiles';
        value: number | CandidateProfile;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  company?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  company?: T;
  description?: T;
  shortDescription?: T;
  category?: T;
  externalId?: T;
  experienceLevel?: T;
  location?:
    | T
    | {
        city?: T;
        canton?: T;
        address?: T;
        postalCode?: T;
        latitude?: T;
        longitude?: T;
      };
  employmentType?: T;
  workload?:
    | T
    | {
        min?: T;
        max?: T;
      };
  workModel?: T;
  salary?:
    | T
    | {
        min?: T;
        max?: T;
        isPublic?: T;
      };
  responsibilities?: T;
  requirements?: T;
  benefits?: T;
  skills?:
    | T
    | {
        skill?: T;
        id?: T;
      };
  applicationUrl?: T;
  applicationEmail?: T;
  status?: T;
  publishedAt?: T;
  expiresAt?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  logoUrl?: T;
  description?: T;
  website?: T;
  industry?: T;
  size?: T;
  location?:
    | T
    | {
        city?: T;
        canton?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  job?: T;
  candidate?: T;
  status?: T;
  message?: T;
  cv?: T;
  coverLetter?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidate-profiles_select".
 */
export interface CandidateProfilesSelect<T extends boolean = true> {
  user?: T;
  summary?: T;
  experiences?:
    | T
    | {
        title?: T;
        company?: T;
        location?: T;
        startDate?: T;
        endDate?: T;
        current?: T;
        description?: T;
        id?: T;
      };
  education?:
    | T
    | {
        degree?: T;
        institution?: T;
        field?: T;
        startDate?: T;
        endDate?: T;
        id?: T;
      };
  skills?:
    | T
    | {
        name?: T;
        level?: T;
        id?: T;
      };
  languages?:
    | T
    | {
        language?: T;
        level?: T;
        id?: T;
      };
  preferences?:
    | T
    | {
        desiredRole?: T;
        desiredSalary?: T;
        desiredWorkload?:
          | T
          | {
              min?: T;
              max?: T;
            };
        desiredLocations?:
          | T
          | {
              location?: T;
              id?: T;
            };
        workModels?: T;
        availableFrom?: T;
      };
  cvFile?: T;
  isPublic?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}